spring:
  application:
    name: veterinaria
  profiles:
    active: production
  datasource:
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 1800000
    validationQuery: SELECT 1
  
---
logging:
  config: classpath:logback-production.xml
spring:
  profiles: production
  datasource:
    jndi-name: java:comp/env/jdbc/veterinaria
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect. org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQLDialect

name: production

---
logging:
  config: classpath:logback-local.xml

spring:
  profiles: local
  
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/gbfood
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    continueOnError: true

name: local

---
logging:
  config: classpath:logback-local.xml

spring:
  profiles: test-db
  
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/gbfood
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    continueOnError: true
    initialize: false

name: test-db

---
logging:
  config: classpath:logback-local.xml

spring:
  profiles: test
  
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    cache: false
  datasource:
    initialize: false
    

name: test