spring:
  application:
    name: veterinaria
  profiles:
    active: production
  
---
logging:
  config: classpath:logback-production.xml
spring:
  profiles: production
  datasource:
    jndi-name: java:comp/env/jdbc/veterinaria
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect. org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQLDialect

name: production

---
logging:
  config: classpath:logback-local.xml

spring:
  profiles: local
  
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/veterinaria
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    continueOnError: true

name: local