/* Generated By:JavaCC: Do not edit this line. DomainFilterValidatorConstants.java */
package es.ucm.visavet.gbf.domains.validator;

public interface DomainFilterValidatorConstants {

  int EOF = 0;
  int PATTERN = 1;
  int AND = 2;
  int OR = 3;
  int NOT = 4;
  int LETTER = 5;
  int DIGIT = 6;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<PATTERN>",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "<LETTER>",
    "<DIGIT>",
    "<token of kind 7>",
    "\"(\"",
    "\")\"",
  };

}
