/* Generated By:JavaCC: Do not edit this line. TopicValidatorConstants.java */
package es.ucm.visavet.gbf.topics.validator;

public interface TopicValidatorConstants {

  int EOF = 0;
  int TERM = 1;
  int LITERAL_TERM = 2;
  int TOPIC_NAME = 3;
  int AND = 4;
  int OR = 5;
  int DIF = 6;
  int ATTYPE = 7;
  int ATLOC = 8;
  int LETTER = 10;
  int DIGIT = 11;
  int WORD = 12;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<TERM>",
    "<LITERAL_TERM>",
    "<TOPIC_NAME>",
    "\"&\"",
    "\"|\"",
    "\"-\"",
    "<ATTYPE>",
    "<ATLOC>",
    "<token of kind 9>",
    "<LETTER>",
    "<DIGIT>",
    "<WORD>",
    "\"(\"",
    "\")\"",
  };

}
