/* Generated By:JavaCC: Do not edit this line. TopicValidatorConstants.java */
package es.ucm.visavet.gbf.topics.validator;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TopicValidatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TERM = 1;
  /** RegularExpression Id. */
  int LITERAL_TERM = 2;
  /** RegularExpression Id. */
  int TOPIC_NAME = 3;
  /** RegularExpression Id. */
  int AND = 4;
  /** RegularExpression Id. */
  int OR = 5;
  /** RegularExpression Id. */
  int DIF = 6;
  /** RegularExpression Id. */
  int ATTYPE = 7;
  /** RegularExpression Id. */
  int ATLOC = 8;
  /** RegularExpression Id. */
  int ESCSEQ = 10;
  /** RegularExpression Id. */
  int WCHAR = 11;
  /** RegularExpression Id. */
  int WORD = 12;
  /** RegularExpression Id. */
  int QESCSEQ = 13;
  /** RegularExpression Id. */
  int QWCHAR = 14;
  /** RegularExpression Id. */
  int QWORD = 15;
  /** RegularExpression Id. */
  int LESCSEQ = 16;
  /** RegularExpression Id. */
  int LWCHAR = 17;
  /** RegularExpression Id. */
  int LWORD = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<TERM>",
    "<LITERAL_TERM>",
    "<TOPIC_NAME>",
    "\"&\"",
    "\"|\"",
    "\"-\"",
    "<ATTYPE>",
    "<ATLOC>",
    "<token of kind 9>",
    "<ESCSEQ>",
    "<WCHAR>",
    "<WORD>",
    "\"\\\\\\\'\"",
    "<QWCHAR>",
    "<QWORD>",
    "\"\\\\\\\"\"",
    "<LWCHAR>",
    "<LWORD>",
    "\"(\"",
    "\")\"",
  };

}
